### ISSUE TITLE
How to I access the objects in the response from a nested request?

### ISSUE THREAD

**Issue by npearson72** [platanus/angular-restmod#264]
I have the following code:
````
angular.module('myApp').factory 'Product', (restmod) ->
  return restmod.model('api/v1/products').mix
    images: { hasMany: 'Image' }
````
````
angular.module('myApp').factory 'Image', (restmod) ->
  return restmod.model('api/v1/images')
````

In my controller I have:

````
  @edit = ->
    @current = Product.$find($routeParams.id)
    images = @current.images.$fetch()
    console.log images
    console.log images[0]
````

Why does image[0] come out as `undefined`? Clearly the data is there.

![screen shot 2015-02-24 at 9 43 46 pm](https://cloud.githubusercontent.com/assets/1323414/6365104/9f18c4e0-bc6e-11e4-872f-661fbe38a0e0.png)

**Comment by smashercosmo** [comment]
Because it's async opeartion. When you try to get first item in your collection it's not yet filled with data.

**Comment by npearson72** [comment]
So how do I work with it? Sorry if that's a dumb question.. I'm a bit new to JS. Can you show me the what methods to call to access the data?

**Comment by smashercosmo** [comment]
If you want to access your data in template you shouldn't do anything, because of restmod's automatic promise unwrapping. But if you want to access you data in controller, like in your example, you need to do it in callback.

```javascript
images = @current.images.$fetch()
images.$asPromise().then (images) ->
    console.log(images[0])
```
or
```javascript
images = @current.images.$fetch()
images.$then (images) ->
    console.log(images[0])
```

P.S. Honestly I still didn't figure out when to use $asPromise.then and when simply $then. Maybe @iobaixas could explain it one more time))

**Comment by npearson72** [comment]
Works perfectly. Thank you!
