### ISSUE TITLE
Using 'before-save' hook in model doesn't change 'this' before saving

### ISSUE THREAD

**Issue by haffmaestro** [platanus/angular-restmod#280]
```javascript
$hooks: {
      'before-save': function(){
       // code to dynamically change object before saving
        if (this.accrual.enabled) {
            delete this.accrual.enabled;
          } else {
            this.accrual = false;
          }
          if (this.reset.enabled) {
            delete this.reset.enabled;
          } else {
            this.reset = false;
          }
      },
```
had the code above, and it doesn't matter what it does, but it was changing this based on certain variables, problem is that 'this' was sent to the server as the same object as it was when it came in to the 'before-save' call-back.

Fixed it by extending the model and writing my own save method, but this is only a workaround.

**Comment by agustinf** [comment]
You are attempting to change it too late in the [lifecycle](https://github.com/platanus/angular-restmod/blob/master/docs/guides/hooks.md#object-lifecycle), the http request is already formed when the "before-save" callback is called. You should use "before-render".

**Comment by haffmaestro** [comment]
Thanks for the response, I didn't find that intuitive, is it documented somewhere?

**Comment by haffmaestro** [comment]
Nvm @agustinf I found it, but what is before-save meant to do then? In ActiveRecord which I thought this was meant to model somewhat, before-save allows you to change the record.

Anyways, thanks a lot + for the work on restmod! Much appreciated.

**Comment by agustinf** [comment]
Well, I guess there are some specifics where the similarity with ActiveRecord gets broken, mainly because the problem is rather different...(i.e. there's no "render" on a ActiveRecord...). Anyway, I'm with you in the fact we could perhaps improve the naming of the hooks to better mimic ActiveRecord's functionality.

**Comment by smajl** [comment]
Does the `before-save` hook really works as intended in the correct part of the request lifecycle? If I modify any of `this` attributes then my client model changes, but the request is made with the original data. I would assume the **complete opposite** - change data sent to server but keep the original on the client (important because user needs to see and continue modifying unmangled data). What am I doing wrong?

**Comment by waleedasif322** [comment]
I agree with @haffmaestro , naming it `before-save` really had me confused in terms of functionality, I was about to bang my head into the wall lol.
