### ISSUE TITLE
belongsTo assign to parent id sends null to server

### ISSUE THREAD

**Issue by ElliottRoche** [platanus/angular-restmod#317]
In this model a customer belongsTo a pricingGroup
```
App.factory 'Customer', (restmod, $ENV) ->
  restmod.model("/api/v1/companies/#{$ENV.currentCompanyId}/customers").mix
    pricing_group: { belongsTo: 'PricingGroup' }

```

When saving a customer inside a pricing group controller, the customers pricing_group_id is sent as null to the server. 

```
App.controller 'PricingGroupFormCtrl', ($scope, $state, pricingGroup, Customer) ->
  addCustomerToPricingGroup: (customer) ->
      customer.pricing_group_id = $scope.pricingGroup.id
      customer.$save().$then (customer) ->
        $scope.customers.push customer
```

If the belongsTo relationship is removed from the customer model, then the id assignment and $save work fine.

It also works if I save customer.pricing_group as an instance of the pricingGroup object, without any direct id assignment.

Is there a reason for this or is it a bug?

**Comment by ldlsegovia** [comment]
@ElliottRoche try assigning `customer.pricing_group = $scope.pricingGroup` instead of `customer.pricing_group_id = $scope.pricingGroup.id`

Another approach would be...

To set the [urlPrefix](https://github.com/platanus/angular-restmod/blob/master/docs/guides/integration.md#-how-can-i-set-a-common-url-prefix-for-every-resource) with value `"/api/v1/companies/#{$ENV.currentCompanyId}"`

```js
// Customer Factory
Customer = restmod.model('/customers');

// Pricing Group Factory
PricingGroup = restmod.model('/pricing_groups', {
  customers: { hasMany: 'Customer' }
});
```

Then, in your controller

```js
pricingGroupInstance.customers.$create({}) // with customer's attributes
```
