### ISSUE TITLE
how to override the url in has_many relation

### ISSUE THREAD

**Issue by bunzli** [platanus/angular-restmod#59]
I would like that my

``` javascript
parts: { hasMany: 'BikePart' }
```

request to `bikes/3/bike_parts` instead of `bikes/3/parts`

**Comment by smajl** [comment]
@iobaixas @bunzli: Guys, please, can you help me? I have huge problems getting to work this simple response with pre-inlined resource:
```js
{
  id: 1,
  productTags: {
    data: [...], // we use {data: [], metadata: {}} structure for collections
    metadata: {...}
  },
  ...
}
```
My model definition:
```js
...
  return restmod.model('/products').mix({
    productTags: {
      hasMany: 'Tag', mask: 'CU', path: 'tags', source: 'productTags.data'
    },
...
```
After fetching `/products` the `productTags` object gets *restmodized* to array with restmod functions attached. So far good. But whenever I save the the parent `product` resource I get `Collection $decode expected array` error and the `productTags` array is emptied.

Does it only work with structures like:
```js
{ id: 1, inlinedCollection: [...], ... }
```
or I am missing something else here? Help really appreciated.

**Comment by iobaixas** [comment]
Hi @smajl, this is probable because restmod expects **create/update** (POST/PUT) requests to respond with a structure similar to **show** (GET). Could you share with us some sample output from the create request triggered when a new tag is created?

**Comment by smajl** [comment]
@iobaixas Our back-end implementation does not send any body content in create/update/delete responses. I did not see any requirement in docs that restmod requires this and till now (when I am trying to init from inlined collection) it was not a problem. Or you meant something else?

**Comment by iobaixas** [comment]
The packer only works on the root of the request, not on each object that get decoded, so I don't think there is a problem there.

From the error you pasted before (`Collection $decode expected array`), I'm assuming there is a problem when decoding the response from the *POST* request. The problem I think you are experiencing is due to the response from the POST containing some kind of object that gets decoded into the product and messing things up. Masking a property from create/update only prevents it from being sent.

I insist on you sharing the POST response, the problem is probably related to that.

**Comment by smajl** [comment]
To be specific, I am updating, so it's PUT request and response is empty, our backend implementation is not sending any responses on PUT requests - sorry, I can't paste anything.

The stacktrace is:
```
Error: Collection $decode expected array
    at Object.Utils.assert (angular-restmod-bundle.js:4016)
    at Array.$decode (angular-restmod-bundle.js:495)
    at Array.$decode (angular-restmod-bundle.js:1153)
    at Array.$decode (angular-restmod-bundle.js:4086)
    at Model.<anonymous> (angular-restmod-bundle.js:2441)
    at decodeProp (angular-restmod-bundle.js:3594)
    at decode (angular-restmod-bundle.js:3556)
    at Function.decode (angular-restmod-bundle.js:3679)
    at Model.$decode (angular-restmod-bundle.js:1471)
    at Model.$decode (angular-restmod-bundle.js:1153)
```
The problem is that the `$decode` function in `RMExtendedApi` module (line 1151) is fed with empty `_raw` and I don't why and how to prevent it. :( Your help is really appreciated.

**Comment by iobaixas** [comment]
Could you try this:

In your base model add the following hook:

```javascript
hooks: {
  'after-request': function(_req) {
    if(!_req.data) _req.data = {};
  }
}
```

**Comment by smajl** [comment]
Wow, thank you thousand times, seems like **that did the trick**!!!

Final model looks like this:
```javascript
  return restmod.model('/products').mix({
    // I don't even need to mask this, it does not get send on updates
    productTags: { hasMany: 'Tag', source: 'productTags.data' },
    ...
    '$hooks': {
      'after-request': function (_req) {
        if(!_req.data) _req.data = {};
      }
    }
  });
```
Awesome, thanks again, but this was a bit tricky. Is this normal behavior or is our JSON data from server somehow special?

**Comment by iobaixas** [comment]
@smajl, it was a somewhat difficult to spot bug in the serialization module.

Thanks for your feedback!

**Comment by iobaixas** [comment]
@smajl, I'm not sure if the REST standard recommends that POST/PUT requests must return some content. At least in APIs made by us we always return the created/updated object in the response.
